version: '3.8'

services:
  tardis-downloader:
    build:
      context: ../..
      dockerfile: docker/tardis-download/Dockerfile
    container_name: market-tick-tardis-downloader
    environment:
      # Tardis API Configuration
      - TARDIS_API_KEY=${TARDIS_API_KEY:-TD.l6pTDHIcc9fwJZEz.Y7cp7lBSu-pkPEv.55-ZZYvZqtQL7hY.C2-pXYQ6yebRF7M.DwzJ7MFPry-C7Yp.xe1j}
      - TARDIS_BASE_URL=${TARDIS_BASE_URL:-https://datasets.tardis.dev}
      - TARDIS_TIMEOUT=${TARDIS_TIMEOUT:-30}
      - TARDIS_MAX_RETRIES=${TARDIS_MAX_RETRIES:-3}
      
      # GCP Configuration
      - GCP_PROJECT_ID=${GCP_PROJECT_ID:-central-element-323112}
      - GCP_CREDENTIALS_PATH=${GCP_CREDENTIALS_PATH:-/app/central-element-323112-e35fb0ddafe2.json}
      - GCS_BUCKET=${GCS_BUCKET:-market-data-tick}
      - GCS_REGION=${GCS_REGION:-asia-northeast1-c}
      
      # Service Configuration
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_DESTINATION=${LOG_DESTINATION:-local}
      - MAX_CONCURRENT_REQUESTS=${MAX_CONCURRENT_REQUESTS:-2}
      - BATCH_SIZE=${BATCH_SIZE:-1000}
      - MEMORY_EFFICIENT=${MEMORY_EFFICIENT:-false}
      - ENABLE_CACHING=${ENABLE_CACHING:-true}
      - CACHE_TTL=${CACHE_TTL:-3600}
      
      # Data Download Configuration
      - DATA_DIRECTORY=${DATA_DIRECTORY:-/app/data}
      - PARQUET_DIRECTORY=${PARQUET_DIRECTORY:-/app/data/parquet}
      - DOWNLOADS_DIRECTORY=${DOWNLOADS_DIRECTORY:-/app/downloads}
      
      # Tick Data Download Configuration
      - DOWNLOAD_VENUES=${DOWNLOAD_VENUES:-deribit,binance-futures}
      - DOWNLOAD_INSTRUMENT_TYPES=${DOWNLOAD_INSTRUMENT_TYPES:-option,perpetual,spot}
      - DOWNLOAD_DATA_TYPES=${DOWNLOAD_DATA_TYPES:-trades,book_snapshot_5}
      - DOWNLOAD_MAX_INSTRUMENTS=${DOWNLOAD_MAX_INSTRUMENTS:-10}
      - DOWNLOAD_START_DATE=${DOWNLOAD_START_DATE:-2023-05-23}
      - DOWNLOAD_END_DATE=${DOWNLOAD_END_DATE:-2023-05-25}
      
      # Runtime Configuration
      - DEBUG=${DEBUG:-false}
      - TEST_MODE=${TEST_MODE:-false}
    volumes:
      # Mount local data directory for persistence
      - ../../data:/app/data
      # Mount downloads directory
      - ../../downloads:/app/downloads
      # Mount logs directory
      - ../../logs:/app/logs
      # Mount temp directory
      - ../../temp:/app/temp
    restart: "no"  # Don't restart automatically for one-time jobs
    networks:
      - market-tick-network

networks:
  market-tick-network:
    driver: bridge
